#' Nutrient Amounts
#'
#' This is the main data frame. It uses information (by linking) from the FOOD_NAME 
#' table (among others) to identify which nutrients and amounts are recorded 
#' for that food.
#'
#' @format ## `NutrientAmounts`
#' A data frame with 524,675 rows and 7 columns:
#' \describe{
#'   \item{food_id}{Foreign key from FOOD_NAME used to link to many tables in the database}
#'   \item{nutrient_id}{Foreign key from NUTRIENT_NAME used to link to nutrient information }
#'   \item{nutrient_value}{Mean value in 100g, edible portion. (The number of 
#'   decimal places does not reflect the accuracy of the data.).}
#'   \item{standard_error}{Standard error of the mean}
#'   \item{number_of_observations}{Number of samples}
#'   \item{nutrient_source_id}{Identifier code generated by the database for 
#'   the nutrient source}
#'   \item{nutrient_date_of_entry}{Date the data was entered into the database}
#'   
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"NutrientAmounts"

#' Conversion Factors
#'
#' This is a principal data frame. This table contains portion size conversion factors.
#' The conversion factors are food specific multipliers by which the nutrient 
#' values for each food may be multiplied to give the nutrients in described 
#' portions.
#'
#' @format ## `ConversionFactor`
#' A data frame with 19506 rows and 4 columns:
#' \describe{
#'   \item{food_id}{The foreign key from FOOD_NAME that is used to join this 
#'   food type with the other related tables to get more information}
#'   \item{measure_id}{Then id to be joined with 'MEASURE_NAME' data frame to get
#'   information on how the food is being measured and with what quantities}
#'   \item{conversion_factor_value}{The factor by which one would multiply the 
#'   nutrient per 100g to obtain nutrient amounts per the measure described 
#'   (the weight of that food in the measure table divided by 100)}
#'   \item{conv_factor_date_of_entry}{Date the data was entered into the database}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"ConversionFactor"

#' Food Names
#'
#' This is a principal data frame. It stores information about each food in the 
#' database. It contains a description of each food in English and French as 
#' well as dates and comments.
#'
#' @format ## `FoodNames`
#' A data frame with 5691 rows and 10 columns:
#' \describe{
#'   \item{food_id}{Primary key that is used to link the foods in other tables 
#'   to this one}
#'   \item{food_group_id}{Foreign key from FOOD_GROUP to link with the food group's info}
#'   \item{food_source_id}{Foreign key from FOOD_SOURCE to link with the source info}
#'   \item{food_description}{Complete food name in English}
#'   \item{food_description_f}{Complete food name in French}
#'   \item{country_code}{Corresponds to the USDA NDB N/A code}
#'   \item{food_date_of_entry}{Date the food name data was entered into the database}
#'   \item{food_date_of_publication}{Date the food name data was originally published}
#'   \item{scientific_name}{Scientific name of the food}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"FoodNames"

#' Food Groups
#'
#' This data frame is a support or "list" table that is used to link to the FOOD NAME 
#' table. It contains a list of 23 different group headings (in English and 
#' French) based on similar characteristics of the foods.
#'
#' @format ## `FoodGroup`
#' A data frame with 24 rows and 4 columns:
#' \describe{
#'   \item{food_group_id}{The id (primary key) used to link food groups to the 
#'   Food_Name data frame}
#'   \item{food_group_code}{Identifier code for the Canadian Nutrient File food 
#'   groups. There are 23 different CNF food groups}
#'   \item{food_group_name}{Food group name in English}
#'   \item{food_group_name_f}{Food group name in French}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"FoodGroup"

#' Refuse Amounts
#'
#' This is a principal data frame. This table contains the percent of refuse, or 
#' inedible portion, for each food.
#'
#' @format ## `RefuseAmounts`
#' A data frame with 6898 rows and 4 columns:
#' \describe{
#'   \item{food_id}{The foreign key from FOOD_NAME that is used to determine what 
#'   food the particular refuse is for}
#'   \item{refuse_id}{Foreign key from REFUSE_NAME used to connect foods to their 
#'   refuse amounts}
#'   \item{refuse_amount}{The percent fo the portion that is refuse}
#'   \item{refuse_date_of_entry}{Date the data was entered into the database}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"RefuseAmounts"

#' Yield Amounts
#'
#' This is a principal data frame. This file table the yield from refuse and/or 
#' cooking losses assigned to certain foods. These yields are most often used 
#' for food inventory purposes.
#'
#' @format ## `YieldAmounts`
#' A data frame with 1427 rows and 4 columns:
#' \describe{
#'   \item{food_id}{The foreign key from FOOD_NAME that is used to determine what 
#'   food the particular refuse is for}
#'   \item{yield_id}{Foreign key from YIELD_NAME used to connect foods to their 
#'   yield amounts}
#'   \item{yield_amount}{Yield from refuse and/or cooking losses}
#'   \item{yield_date_of_entry}{Date the data was entered into the database}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"YieldAmounts"

#' Food Sources
#'
#' This data frame is a support or "list" table that is used to link to the FOOD_NAME
#' table. It contains a list of several food sources (in English and French) 
#' that foods can be grouped on.
#'
#' @format ## `FoodSources`
#' A data frame with 17 rows and 4 columns:
#' \describe{
#'   \item{food_source_id}{Primary key id used to link foods in other tables with 
#'   respective source}
#'   \item{food_source_code}{Identifier code for the food sources. Food sources 
#'   give an indication as to Canadian content}
#'   \item{food_source_description}{Food Source description in English}
#'   \item{food_source_description_f}{Food Source description in French}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"FoodSources"

#' Nutrient Names
#'
#' This data frame is a support or "list" table that contains the list of nutrients 
#' (in English and French) used in the NUTRIENT_AMOUNT table, with which it is linked.
#'
#' @format ## `NutrientNames`
#' A data frame with 153 rows and 8 columns:
#' \describe{
#'   \item{nutrient_id}{Primary key id used to link foods in other tables with 
#'   respective nutrients}
#'   \item{nutrient_code}{Identifier code for nutrient name descriptions}
#'   \item{nutrient_symbol}{Nutrient symbol or abbreviation of the nutrients. 
#'   They may differ from international nomenclature.}
#'   \item{nutrient_unit}{Unit of measure (e.g., mg, g, mcg)}
#'   \item{nutrient_name}{Nutrient name in English}
#'   \item{nutrient_name_f}{Nutrient name in French}
#'   \item{tagname}{International Network of Food Data Systems (INFOODS) Tagnames. 
#'   A unique Abbreviation for a food component developed by INFOODS to aid in 
#'   the interchange of data. 
#'   http://www.fao.org/infoods/infoods/standards-guidelines/food-component-identifiers-tagnames/en/}
#'   \item{nutrient_decimals}{Number of decimal places used in the rounding of 
#'   the nutrient value}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"NutrientNames"

#' Nutrient Sources
#'
#' This data frame is a support or "list" table that is used to link to the NUTRIENT_AMOUNT 
#' table It contains a list of several sources and/or types of nutrient data 
#' (in English and French).
#'
#' @format ## `NutrientSources`
#' A data frame with 21 rows and 4 columns:
#' \describe{
#'   \item{nutrient_source_id}{Primary key id used to link nutrients in other 
#'   tables with respective source}
#'   \item{nutrient_source_code}{Identifier code for nutrient source descriptions.}
#'   \item{nutrient_source_description}{Nutrient Source description in English}
#'   \item{nutrient_source_description_f}{Nutrient Source description in French}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"NutrientSources"

#' Measure Names
#'
#' This data frame is a support or "list" table that is used to link to the 
#' CONVERSION_FACTOR table. It contains a list of measures (in English and French).
#'
#' @format ## `MeasureNames`
#' A data frame with 1163 rows and 3 columns:
#' \describe{
#'   \item{measure_id}{Primary key id used to link foods to measures when using 
#'   conversion factor to measure nutrient, yield or refuse amounts}
#'   \item{measure_name}{Measure description in English}
#'   \item{measure_name_f}{Measure description in French}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"MeasureNames"

#' Refuse Names
#'
#' This file is a support or "list" table that is used to link to the REFUSE_AMOUNT 
#' table. It contains a list of refuse types.
#'
#' @format ## `RefuseNames`
#' A data frame with 151 rows and 3 columns:
#' \describe{
#'   \item{refuse_id}{Primary key used to link foods to their corresponding 
#'   refuse type}
#'   \item{refuse_name}{Refuse description in English}
#'   \item{refuse_name_f}{Refuse description in French}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"RefuseNames"

#' Yield Names
#'
#' This data frame is a support or "list" table that is used to link to the YIELD_AMOUNT 
#' table. It contains a list of yield types or yield descriptions (in English and French).
#'
#' @format ## `YieldNames`
#' A data frame with 80 rows and 3 columns:
#' \describe{
#'   \item{yield_id}{Primary key used to link foods to their corresponding 
#'   yield type}
#'   \item{yield_name}{Yield description in English}
#'   \item{yield_name_f}{Yield description in French}
#'   ...
#' }
#' @source <https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html>
"YieldNames"

